evgMrmApp/src/devSupport/devEvgSoftSeq.cpp

By RRM, write_mbbo device support routine returns the following values:
0: Success.
Other: Error.
The default return value for write_mbbo_runMode function is 2, which causes an error to be reported regardless of write operation succeeding or not. Changing the default return value to 0 fixes the issue.
read_mbbi device support routine returns a value of 2 if no conversion is performed, hence it is unchanged.

Fix the device support for EVG Run Mode

---

evrMrmApp/src/drvem.cpp

Timestamp seconds value is converted before checks are finished. This can cause lastInvalidTimestamp to hold converted value and result in inconsistent comparison later on.

Make POSIX time conversion only after all checks

---

evgMrmApp/src/evgSequencer/evgSoftSeq.cpp
evrMrmApp/src/drvem.cpp

There is an issue when performing a Commit operation on an Enabled, Loaded sequencer. Commit sometimes causes the sequencer to run without external trigger. At NSLS-II, this triggers ACMI fault to appear spontaneously when changes are made which require sequencer commit, e.g. changing the target injection bucket. ACMI fault means that certain event does not arrive at expected times. Troubleshooting has shown that this event indeed arrived not when expected.
Testing:
With EVG using FracSyn source, Mxc divider was set to obtain ~0.1 Hz frequency (the glitch occurs at 1 Hz as well, but at much lower rate). Sequencer table containing event 25 with timestamp 14 (and other events) was used and assigned to trigger from Mxc in Single Run mode. To rearm the sequencer, single shot controller logic …

Disable sequencer before syncing

---

evgMrmApp/src/devSupport/devEvgMrm.cpp

Allow evgMrm stringin device support to set record's time-stamp.
Does it make sense to only set the time-stamp like this when the evg is in no-alarm status?

Add support for deviceTime

---

evrMrmApp/src/evrRegMap.h

June 19 datasheet shows offset difference between MapRam1 and MapRam2 is 0x1000 not 0x2000

fix datasheet mismatch

---

documentation/evr-usage.lyx
evrMrmApp/Db/Makefile
evrMrmApp/Db/mrmevrtsbuf.db
evrMrmApp/src/Makefile
evrMrmApp/src/drvem.cpp
evrMrmApp/src/drvem.h
evrMrmApp/src/drvemTSBuffer.cpp
evrMrmApp/src/drvemTSBuffer.h

Adds the ability to configure per-event buffering of event RX timestamps, with readout as a batch (in a `waveformRecord`).  Batches are marked either by a manually via a record, or by a reception of second "flush" event code.  Times are double buffered, so results will remain stable during readout.  Buffer depth is determined by the largest `NELM` among the waveformRecords associated with a buffer.  There is a per-buffer overflow counter.
Events times may be encoded into a waveformRecord in three ways: TimesRelFirst, TimesRelFlush, or TimesRelPrevFlush.

Add buffered capture of event timestamps

---

evrApp/Db/evrscale.db

at the moment, changing prescaler's Div-SP causes PhasOffs-CO_ to reset
prescaler's phase-offset to 0 if user used PhasOffs:Raw-SP to set it.
Fix this, by hanging Div-RB CPP on -RB not on -SP.

fix EVR PhasOffs processing

---

mrmShared/linux/mrf.h
mrmShared/linux/uio_mrf.c

As per #44, this is a PR that introduces `struct pci_error_handlers` and its rudimentary callbacks that result in AER process to successfully restore the PCI register space of a mTCA MRF EVR after a bus reset was issued due to detection of a PCIe error.
Without handling the AER the PCI device makes the recovery process fail, even if all the other device on path to recovery can handle AER.
I do not have sufficient knowledge of the internals of the MRF kernel driver and its interaction with the card/firmware hence the `mrf_error_detected()` and `mrf_slot_reset()` might need to do a bit more than just disabling/enabling the PCI device.
This code was tested with the https://git.kernel.org/pub/scm/linux/kernel/git/gong.chen/aer-inject.git on a mTCA form factor of EVR (mTCA-EVR-300).

minimal AER handling functionality

---

evrMrmApp/src/drvemCML.cpp

This change sets word length and mult to correct values for mTCA form factor

Fix CML parameters to handle mTCA GTX correctly

---

.github/workflows/ci-scripts-build.yml
.github/workflows/linux-build.yml

@mdavidsaver, @gabrielfedel
1) ubuntu 16 is removed
2) manual trigger is added for eventual test runs (harmless)
3) ubuntu-latest and latest linux build feature added, just to know when the compatibility gets issues in advance
Please, check new: 
* [ci-scripts output](https://github.com/jerzyjamroz/mrfioc2/actions/runs/6196075333)
* [linux-build output](https://github.com/jerzyjamroz/mrfioc2/actions/runs/6196200569)

ci: Removal of the unsupported Ubuntu 16.04 and update to the latest within github workflows.

---

evgMrmApp/Db/evgInput.db
evgMrmApp/Db/evgMxc.db
evgMrmApp/Db/evgSoftSeq.template
evrMrmApp/Db/mrmevrtsbuf.db

```
* fix: $(SYS){$(D)} changed to $(PP=$(SYS){$(D)}).
* fix: $(PP=$(SYS){$(D)-)EvtClk$(s=}) introduced.
* PP is a prefix-prefix so base prefix always that cannot be assigned in the iterative ways within .substitutions.
```

fix: $(SYS) and {$(D)} addressed with PP

---

evrMrmApp/src/drvemPulser.cpp

EVM EVRU and EVRD clock registry is empty, it means it is needed a mechanism to resolve it.

fix: Better handling of the clocks for EVR widths and delays. 

---

evgMrmApp/Db/cpci-evg-300.substitutions
evgMrmApp/Db/mtca-evm-300.substitutions
evgMrmApp/Db/vme-evg230-nsls2.substitutions
evgMrmApp/Db/vme-evg230.substitutions

evgEvtClk.db uses a RFIDV macro instead of FDIV.

Fix RFDIV macro

---

mrfCommon/src/mrf/version.h

This change does not affect the actuall compilation at all. It adds a possibility to compile the project without using the perl script.

feat: version.h added to support external compilations.

---

mrmShared/src/mrmSeq.cpp

If an action was unsuccesfull display the error on the GUI (not just in the IOC shell). Clear if no errors occured.
This error display is supposed to be just an information for the user.

Display softseq errors on the GUI

---

evrMrmApp/src/drvem.cpp

* TCLKA and TCLKB should use UNIV16,17 and CMLs.
* Better handling of the fractional synthesizer configuration - useful for EVRD and EVRU as they do not have all the registers functional.

fix: TCLKA and TCLKB and EVRU/EVRD clocks.

---

evrApp/src/devEvrStringIO.cpp
mrfCommon/src/mrfCommon.h

Time-I displays the time without the ms part which means it has to be rounded accordingly.

fix: Normalize the Time-I record timestamp to 1s.

---

mrfCommon/src/mrfCommon.cpp
mrfCommon/src/mrfCommon.h

To allow for more than 128 versions of FW minor releases, the `m_minor` variable type is changed from `epicsInt8` to `epicsUInt8`.

Changing minor FW version variable to unsigned

---

evrApp/src/devEvrEvent.cpp

While trying to build `master` branch  at commit d6cdcbf0798e18b08bbf608e6cd5d9be68b6cf59 with EPICS base `7.0.5` I got the following error:
```
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET   -D_X86_64_  -DUNIX  -Dlinux      -O3 -g   -Wall      -mtune=generic      -m64  -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/gcc -I../../../include/os/Linux -I../../../include   -I/opt/epics7/modules/devlib2/include -I/opt/epics7/base/include/compiler/gcc -I/opt/epics7/base/include/os/Linux -I/opt/epics7/base/include     -I../../../mrfCommon/src    -c ../evrMain.cpp
/usr/bin/g++  -D_GNU_SOURCE -D_DEFAULT_SOURCE         -DUSE_TYPED_RSET   -D_X86_64_  -DUNIX  -Dlinux      -O3 -g   -Wall      -mtune=generic      -m64  -I. -I../O.Common -I. -I. -I.. …
```

Changes for UTAG compatibility with base 7.0.5 and earlier

---

evrApp/Db/evrpulser.db
evrApp/src/evr.cpp
evrApp/src/evr/pulser.h
evrFRIBApp/src/evr_frib.h
evrMrmApp/src/drvemPulser.cpp
evrMrmApp/src/drvemPulser.h
evrMrmApp/src/evrRegMap.h

Add prescaler and DBus bit triggers for pulsers

Pulser trigger with DBus bits and prescalers

---

evgMrmApp/src/Makefile
evgMrmApp/src/evgInit.cpp
evgMrmApp/src/evgMrm.h
evrApp/Db/evrevent.db
evrApp/Db/evreventutag.db
mrfCommon/src/Makefile

- Until EVM-EVRU/D interrupts are implemented in the EVM, the irqpoller will be delivering the capability.
- SFTSEN macro allows to use of the software timestamp.

fix: EVRU/D use the irqpoller until the isr is implemented.

---

evgMrmApp/src/evgInit.cpp

- Most users will not use this feature so the resources are released by default.
- It allows configuring the irq polling period of EVRU/D.

feat: Macros controlling the EVRU/D irqpoller.

---

evgMrmApp/src/evgMxc.cpp

The setFrequency command doesn't set the correct prescaler and so the frequency, because the prescaler is wrongly computed. 
We need to use the  `m_owner->GetFrequency` and not `getFrequency()`, otherwise we obtain a frequency that is not correct and change according to the prescaler computed.
It seems you are using git cliff, so I've tried to use a correct commit message, tell me if its ok otherwise I can change it.

fix: Correct the setFrequency command

---

evrMrmApp/Db/evr-mtca-300u.substitutions
evrMrmApp/Db/evr-mtca-300u.uv.substitutions

It adds function set and reset, planned in the substitutions files. 
It also adds missing inputs : The four possible universal inputs and the 8 backplane inputs.
This version has been tested in labo and another version of mrfioc2 with similar modifications has been used in production since 3 years.

Complete MTCA EVR300U substitution file 

---

README.md
documentation/mainpage.h
scripts/pushdoc.sh

Update documentation and README.md to remove reference to source forge and point to github pages.
Also updated pushdoc script to be compatible with githubpages

Update documentation to remove reference to source forge

---

evgMrmApp/Db/evgInput.db
evgMrmApp/Db/evm-mtca-300-evr.uv.substitutions
evgMrmApp/src/evg.cpp
evgMrmApp/src/evgInput.cpp
evgMrmApp/src/evgInput.h
evgMrmApp/src/evgRegMap.h
iocBoot/iocseqmask/Makefile
iocBoot/iocseqmask/st_EVM.cmd
iocBoot/iocseqmask/st_EVR.cmd
mrmShared/Db/mrmSoftSeq.template
mrmShared/src/mrmSeq.cpp

This PR add mask (and enable) functionalities for the sequencer. See chapter **2.4 Event Sequence**r (of the 2021 manual maybe it's updated now)
It add possibility of the sofware mask/enable (register SQSWMASK and SQSWENA) and mask attached to physical input. See register FP0SQMK and FP0SQEEN.
I've added and iocseqmask to have an example. It works with an MTCA EVM300 and MTCA EVR300U, using backplanes as physical input and output.
For SARAF MPS we are using the mask functionnality to stop producing the chopper pulse, stop the magnetron, but not stopping RF, so we are masking events of the sequence without stopping the sequencer.

Add featuring masks/enable

---

.github/workflows/release-dkms-deb-package.yml
.github/workflows/release-dkms-rpm-package.yml
mrmShared/linux/debian/rules
mrmShared/linux/dkms-rpm/mrf.spec.in

This PR includes:
* Small change to make the deb package compatible with old debian version
* Changes on rpm spec file to allow it be built correctly on github actions
* Include actions to release the deb and rpm packages for dkms kernel module
Some points about the release of the packages:
* They should be attached to a tag . I have set the deb tag as kmod-*d* (for example kmod-3-d0), and the rpm tag as kmod-*r* (for example kmod-3-r1)
* All the release also will have the all the source code
These 2 points are a bit annoying, but I think to avoid them it will require a bit of work to implement an workflow (right now we are using one that already exists).
As an example 2 releases, one for deb and one for rpm:
https://github.com/gabrielfedel/mrfioc2/releases/tag/kmod-3-r1 …

build: Include action to release deb and rpm dkms packages

---

evrApp/src/Makefile
mrfApp/src/Makefile

This dbd is used by the evreventutag.db, and without this fix the mrf.dbd wouldn't have it included. The change also include it to be built on dbd folder

fix: Fix inclusion of evrSupportBase7.dbd

---

evrMrmApp/src/drvem.cpp

@Insomnia1437 - please, review.

fix: Use softclock if the registry empty for EVRU/D.

---

Makefile

Because of the internal EVRs in the EVMs, evgMrmApp depends on evrApp (through substitutions files). On a classical sequential compilation it is working, but on our Nix environment the compilation can be parallelized and sometimes we have compilation error because of this dependency.
```
-S../mtca-evm-300.substitutions
ERROR msi: Can't open file 'evrbase.db'
```
this modification should be transparent for classical compilation.
Is it possible to increase tag if merge is accepted please ? (minor 2.6.1)
Thanks

add evgMrmShared depends also on evrApp because of internval EVRs

---

mrfCommon/src/genVersionHeader.pl

This patch adds a logic to only use latest git tag which begins with a number as a mrfioc2 version string (inside `include/mrf/version.h`), so this excludes tags like `kmod-rpm*`.  See #145 
Also, `dirty` string is removed because it is confusing.

fix: version fetched from only digital git tags

---

evgMrmApp/src/evgInit.cpp
evgMrmApp/src/evgMrm.cpp
evgMrmApp/src/evgMxc.cpp
mrfCommon/src/mrfcsr.h

1: Adding configurations for EVM-VME-300 card so that it can be configured using mrmEvgSetupVME
2: Updated the board ID determination for the 300-series VME boards
3: The vxWorks compiler does not support C99, so functions like lround cannot be called. I added the vxWorks specific code where lround is called.

EVM-VME-300 Support

---

evrMrmApp/src/evrRegMap.h

Fixed a typo in 
\#define U32_EventLog(N)    (U32_EventLog_base + (N))
Updated a few macros because of the capacities of new hardware
\#  define PulserMax 24
\#  define OutputCMLMax 4

Fixing the macros in evrRegMap.h

---

evgMrmApp/Db/evgAcTrig.db
evgMrmApp/src/evgAcTrig.cpp
evgMrmApp/src/evgAcTrig.h
evgMrmApp/src/evgRegMap.h

I found a bug in the code. When trig event source is selected as AC Trig, it didn't generate any events. I looked through the manual and found the address of the AcTrigMap, and found that the Mask and Shift are not correct. 
Macros AcTrigMap_EvtMASK and AcTrigMap_EvtSHIFT are corrected.
After this fix, I added the feature to allow external synchronization sources for the AC trig, in another commit.
After these changes, I tested them and they worked.

Fixed the AcTrigMap and added more options to AcTrig Sync Source

---

evgMrmApp/src/evgMrm.cpp
evrMrmApp/src/drvem.cpp
mrfCommon/src/flashiocsh.cpp

Add the flash IO for the EVM-VME-300 and EVR-VME-300.
Only cards with pci buses can have flash IO before. I just make it also available for cards with VME bus and firmware version higher than 2.0.

Add the FLASH IO for the vme300 boards

---

evgMrmApp/Db/evm-fct.template
evgMrmApp/src/fct.cpp
evgMrmApp/src/fct.h

This feature allows us to set a target delay of an EVM and it will adjust its FIFO depth to compensate the delay. This allows people to have a partial delay compensation for devices with embedded EVRs that do not support delay compensation.

Added the feature of setting a delay target for an EVM

---

mrmShared/linux/.gitignore
mrmShared/linux/uio_mrf.c

From Linux kernel version 6.3 onward the `vma->vm_flags` are private; `vm_flags_set()` should be used instead.
After compilation I see `mrf.mod` that was not in `.gitignore`; added.
Tested on a local crate running Linux kernel version 6.7.

mrf kernel driver updates for kernels 6.3+

---

evgMrmApp/Db/evgInput.db
evgMrmApp/src/evg.cpp
evgMrmApp/src/evgInput.cpp
evgMrmApp/src/evgInput.h
evgMrmApp/src/evgRegMap.h

This feature allows people to use an external signal to reset the multplexed counters. 
This feature is only functional with firmware version 207.11. The earlier FW had a bug.

Adding the hardware Mxc reset function for each input

---

mrfCommon/src/flash.cpp

This commit fixes access out of bonds from flash.cpp.
With this fix it is possible to use the flash functions (write and info)
with source compile with gcc >= 11

Correct access out of bonds on buffer used by flash functions

---

README.md
documentation/mainpage.h

This PR adds the work of:
* @jpietari within https://github.com/jpietari/mrf-firmware
* @ttkorhonen within https://mrftiming.readthedocs.io/en/latest/index.html
* Updates the obsolete part

docs: mrf-firmware and Readthedocs references added.

---

evgMrmApp/src/evgInit.cpp

Even though the evm-vme-300 does not have physical UNIV I/O channels, it does have the channels logically that can be used as interfaces with the EVRU and EVRD. This commit changes the number of UNIV I/O of vme-300 from 0 to 16.

adding virtual univ inputs for EVM-VME-300 for EVRU/D event forwarding

---

evgMrmApp/Db/evgMrm.db
evgMrmApp/src/evg.cpp
evgMrmApp/src/evgMrm.cpp
evgMrmApp/src/evgMrm.h

If the reference clock has a glitch (a forward shift of phase), the event clock is down and the EVM ends up in a state where it cannot automatically recover the event clock even the PLL status shows fine. To fix this, the FracSynth control word must be rewritten. Writing to that register triggers some low-level reset of the board and the event clock is recovered after that. 
In the current code, writing to the record of the Frac Synth frequency does not result in writing to the control word register, because it checks if the requested frequency value changes. I had to write a different frequency and write back the old value. This is inconvenient and likely to introduce error when I just need a reset. In this commit, I made a dedicated api function and a record to write the same control …

Add the EVM frac Synth reset function

---

evrMrmApp/Db/Makefile
evrMrmApp/Db/evr-mtca-300u.uv.substitutions
evrMrmApp/Db/evr-vme-300.substitutions
evrMrmApp/Db/mrmevrdlymodule.template
evrMrmApp/Db/mrmevrout.db
evrMrmApp/Db/mrmevroutdly.db
evrMrmApp/src/drvem.h
evrMrmApp/src/drvemOutput.cpp
evrMrmApp/src/drvemOutput.h
evrMrmApp/src/evrRegMap.h

MRF has a new transition board that supports the delay tuning of daughter cards. With this new board, for a daughter card that has the delay-tuning feature (like the TTL-DLY and PECL-DLY modules), the delay of the transition board channel can be controlled by an register in the EVR board. The previous version of the TB does not support the fine delay tuning even if the daughter card has the delay tuning. 
In this PR, I have 3 commits, for the EVR registers, API functions and EPICS records. The last commit makes the front panel UNIV channels share the same fine-delay tuning interface.

feat: Fine delay for rear transition board

---

evrMrmApp/src/drvemCML.cpp

The original PR #157 (https://github.com/epics-modules/mrfioc2/pull/157) is moved here.
Quoted from PR #157:
Because the EVR-VME230 uses 20bit CML word rather than 40bit, I need to handle this exception for the VME64 form factor.
In the setPattern function for waveform mode, the bits and word arrangement does not work for the EVR-VME300. Since I don't have a EVR-VME230RF card at hand, it is hard for me to decide if it is an generic difference between the firmware versions. Therefore, I kept the old code only for the firmware version of the 230-series hardware.
Will people at ESS test if this patch works for the mtca EVR? (This change only affects the waveform mode, not the 4x pattern or the frequency mode.)

CML/GTX supports for EVR-VME300

---

evgMrmApp/Db/evgDbus.db
evgMrmApp/Db/evgInput.db
evgMrmApp/Db/evm-mtca-300.uv.substitutions
evgMrmApp/Db/evm-vme-300.substitutions
evrMrmApp/Db/evr-vme-300.substitutions

Updates for consistency:
1: In the evr-vme-300 substitution file, for the transition board output records, TBUV is changed to RBUV because the objects in the drivers are like RearInput.
2: Added Univ11-15 to the DBus source selection, so that all Univ inputs can be used. Mainly for EVRU and EVRD interface
Bug fix:
1: Fixed the FLNK filed of the Mxc reset enable for hardware input channels
2: Fixed the evm-vme-300 substitution file regarding the bit assignment for the 1 Pps source.

db file update and bug fix

---

evgMrmApp/Db/evgDbus.db
evrMrmApp/Db/evr-vme-300.substitutions

Fixing two bugs discovered during the screen development:
1: The extra two dbus sel records are missing the associated mbbi record. Added them.
2: For the CML records, the name of the associated output records needs an update: FPUV06 to FPUV6, FPUV07 to FPUV7.

fix: Add mbbi record for evg Dbus source sel. Fix the EVR record name for CML

---

opi/bob/evg/_evg_dbus.bob
opi/bob/evg/_evg_input_full.bob
opi/bob/evg/_evg_mxc_vme300.bob
opi/bob/evg/_evg_trigevt_vme300.bob
opi/bob/evg/evm-vme-300-evr.bob
opi/bob/evg/evm-vme-300-input-expert.bob
opi/bob/evg/evm-vme-300-vinput-expert.bob
opi/bob/evg/evm-vme-300.bob
opi/bob/evr/_evrdlygen_withgate.bob
opi/bob/evr/_evrinput_vme300.bob
opi/bob/evr/_evroutput_finedelay.bob
opi/bob/evr/_evroutput_vme300.bob
opi/bob/evr/_evroutputdelaymodule.bob
opi/bob/evr/_evrvirtualgate.bob
opi/bob/evr/evr-cml-pat40.bob
opi/bob/evr/evr-expert.bob
opi/bob/evr/evr-vme-300.bob
opi/bob/evr/evr-vme300-cml-output.bob
opi/bob/launcher.bob

1: Some of the existing screens (mostly subscreens) are updated: fixing version compatibility, color and size
2: Added screens and subscreens for evm-vme-300
3: Added screens and subscreens for evr-vme-300
The screens for the mtca cards are mostly intact. I made minimal size adjustments to make things fit.

Screen files for vme-300 EVM and EVR

---

evrMrmApp/Db/evr-vme-300.substitutions
opi/bob/evg/_evg_dbus.bob
opi/bob/evr/evr-vme-300.bob

In commit 56a314d1d72bc6cc55becebfb3a3e975fae4dcae, the Omsl-FOut records for DBus are refactored. 
In this PR, the corresponding pv in dbus subscreen is updated. 
Also combine with two small corrections.
1: A typo in the evr-vme-300 substitution file. 
2: Default tabs for pulser and I/O in evr-vme-300 screen file.

Fix the pv name in the dbus subscreen after the refactor of Omsl-Fout

---

evrMrmApp/Db/Makefile
mrmShared/Db/Makefile

In APS we use many db and template files from the installed area to build our own data base. These files are needed by our build system.

adding more db and template files to the install directory

---

evgMrmApp/Db/evgSoftSeq.template

This bug was probably introduced when I added the source 2 of the trigger source. The OUT links of the all sel records should be the same, so the macro s should not be in the OUT link.
I didn't notice this because in my test stand s="". After I fully built my db file at APS where I need to use the macro "s", I found this issue.

bug fix: remove macro s in Seq Trigger Source Selection OUT link

---

mrmShared/linux/uio_mrf.c

Recently AlmaLinux 9.5 is released, during test, I found that the backport of `vm_flags_set()` actually starts from RHEL 9.5. 
`RHEL_RELEASE_CODE` should match that accordingly.

fix driver error on rhel95
